project:
  type: website

website:
  title: "Dataviz Blog"
  navbar:
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

author:
  - name: Ashwin Malshe
    url: https://business.utsa.edu/faculty/profiles/malshe-ashwin.html
    
format:
  html:
    theme:
      - default
      - styles.scss
      
editor: source
